const fs = require("fs");
const path = require("path");
const FILE = path.join(__dirname, "../data/credentials.json");
if (!fs.existsSync(path.dirname(FILE))) {
  fs.mkdirSync(path.dirname(FILE), { recursive: true });
}
const credentialStore = {
  save(entry) {
    const all = this.getAll();
    // Since entry contains the n8n credential ID as 'id', putting '...entry' last
    // ensures it overrides the default autogenerated id.
    all.push({ id: Date.now().toString(), createdAt: new Date().toISOString(), ...entry });
    fs.writeFileSync(FILE, JSON.stringify(all, null, 2));
  },
  getAll() {
    if (!fs.existsSync(FILE)) return [];
    return JSON.parse(fs.readFileSync(FILE, "utf-8"));
  },
  delete(id) {
    const all = this.getAll().filter(c => c.id !== id);
    fs.writeFileSync(FILE, JSON.stringify(all, null, 2));
  }
};
module.exports = credentialStore;
